### ISSUE TITLE
How to set default mode?

### ISSUE THREAD

**Issue by Pound-Hash** [andreyorst/smarttab.kak#13]
I understand that this plugin provides commands. I can run these commands manually from within a Kakoune buffer. But how do I set one of the commands in my `kakrc` so it becomes the default? For example, I added `expandtab` at the end of my `kakrc`, but it didn't work. Also, I don't think I can set `expandtab` as an option a la, `set-option global expandtab`. So how can I do it?

Thanks

**Comment by andreyorst** [comment]
all these commands operate on a buffer level, so you need a hook that will run on each new buffer. Probably something like this should do:

```kakscript
hook global BufOpenFile .* expandtab
hook global BufNewFile  .* expandtab
```

**Comment by Pound-Hash** [comment]
Yes, that works, at least on my initial attempt.

Thanks
