### ISSUE TITLE
Command to get the current mode?

### ISSUE THREAD

**Issue by dpc** [andreyorst/smarttab.kak#3]
I'm trying to debug some hooks that trigger this, and I need to know which mode was actually selected. :)

**Comment by andreyorst** [comment]
can you please provide an example of what you're trying to achieve?

**Comment by dpc** [comment]
`:getsmarttabmode`

Prints:

`smarttabs` (or whatever is the current mode)

in status bar. :)

**Comment by andreyorst** [comment]
I mean what are you want to do that involves automatic switching depending on current mode?

I can add an option that prints mode, but I think it'll be confusing that setting this option isn't hanging mode

**Comment by dpc** [comment]
I had a bug in my hooks regex, and I was getting different mode than I wanted. The regex was the problem, but it wasn't immediately obvious which mode I'm in.

I have actually configured "displaying whitespaces" now, and eventually fixed my regex. But at that point it would be great to be able to query the current mode somehow.

If this is not idiomatic or something, then let's just forget about it. It was just a thought.

**Comment by dpc** [comment]
Thanks!
