### ISSUE TITLE
[FEATURE] SmartTab Powerline Indicator

### ISSUE THREAD

**Issue by insipx** [andreyorst/smarttab.kak#4]
I've created a tabs-spaces-smarttab indicator for my powerline config for my own use here: https://github.com/insipx/dotfiles/blob/master/.config/kak/config/90-powerline.kak

I think it may be cool to integrate it into this plugin -- if so, i'll create a PR!

**Comment by andreyorst** [comment]
Sure! that would be a nice Xmas gift!
