### ISSUE TITLE
Settings are per window should be per buffer

### ISSUE THREAD

**Issue by ficoos** [andreyorst/smarttab.kak#5]

**Comment by andreyorst** [comment]
I made it per window because filetype is usually set up with `winsetoption` hooks

**Comment by ficoos** [comment]
This means the function fails when opening a file before the first window is open.
Also trying to align it with [editorconfig](https://github.com/mawww/kakoune/blob/master/rc/extra/editorconfig.kak) settings becomes asymmetrical as it uses buffers as scope. Also, IMHO it's an odd setting to set differently for different windows. Why would you want this setting to change when moving to a different client?

**Comment by andreyorst** [comment]
Can you test [buffer branch](https://github.com/andreyorst/smarttab.kak/tree/buffer) please?

**Comment by ficoos** [comment]
Works for me.

**Comment by andreyorst** [comment]
however setting `indentwidth` per buffer doesn't seem to work
